export const ImageFilesData = {
    logo: require("../assets/images/wiyanwhite.png"),
    drawerbackground:require("../assets/images/menu-bg.png"),
    profileImagedrawer:require('../assets/images/user-profile.jpg'),
    headerlogo:require('../assets/images/headerlog.png'),
    menu:require('../assets/images/menu.png'),
    categoryheader:require('../assets/images/categoryheader.png'),
    loudspeaker:require('../../imgss/loudspeaker.png'),
    weightlifting:require('../../imgss/weightlifting.png'),
    makeup:require('../../imgss/makeup.png'),
    massage:require('../../imgss/massage.png'),
    restaurant:require('../../imgss/restaurant.png'),
    subcate_app_logo: require("../assets/images/subcat_app_logo.png"),
    subcate_banner: require("../assets/images/subcat_banner.png"),
    subcate_image1: require("../assets/images/image1.png"),
    subcate_image2: require("../assets/images/image2.png"),
    subcate_image3: require("../assets/images/image3.png"),
    subcate_image4: require("../assets/images/image4.png"),
    subcate_image5: require("../assets/images/image5.png"),
    subcate_image6: require("../assets/images/image6.png"),
    subcate_image7: require("../assets/images/image7.png"),
    subcate_image8: require("../assets/images/image8.png"),
    subcate_image9: require("../assets/images/image9.png"),
    subcate_image12: require("../assets/images/image12.png"),
    subcate_image13: require("../assets/images/image13.png"),
    subcate_image14: require("../assets/images/image14.png"),
    subcate_image15: require("../assets/images/image15.png"),
    userimg: require("../assets/images/Union1.png"),
    notemedical: require("../assets/images/note-medical.png"),
    globe: require("../assets/images/globe.png"),
    bell: require("../assets/images/bell.png"),
    handshake: require("../assets/images/handshake.png"),
    marker: require("../assets/images/marker.png"),
    megaphone: require("../assets/images/megaphone1.png"),
    memopad: require("../assets/images/memo-pad.png"),
    notemedical: require("../assets/images/note-medical.png"),
    shieldexclamation: require("../assets/images/shield-exclamation.png"),
    messagesdollar: require("../assets/images/messages-dollar.png"),
    squarestar: require("../assets/images/square-star.png"),
    Union3: require("../assets/images/Union3.png"),
    Union2: require("../assets/images/Union2.png"),
    Union4: require("../assets/images/Union4.png"),


  };
//const logo = require("../assets/images/wiyanwhite.png");

