export const ImageFilesData = {
    logo: require("../assets/images/wiyanwhite.png"),
    drawerbackground:require("../assets/images/menu-bg.png"),
    profileImagedrawer:require('../assets/images/user-profile.jpg'),
    headerlogo:require('../assets/images/headerlog.png'),
    menu:require('../assets/images/menu.png'),
    categoryheader:require('../assets/images/categoryheader.png'),
    loudspeaker:require('../../imgss/loudspeaker.png'),
    weightlifting:require('../../imgss/weightlifting.png'),
    makeup:require('../../imgss/makeup.png'),
    massage:require('../../imgss/massage.png'),
    restaurant:require('../../imgss/restaurant.png'),
    subcate_app_logo: require("../assets/images/subcat_app_logo.png"),
    subcate_banner: require("../assets/images/subcat_banner.png"),
    subcate_image1: require("../assets/images/image1.png"),
    subcate_image2: require("../assets/images/image2.png"),
    subcate_image3: require("../assets/images/image3.png"),
    subcate_image4: require("../assets/images/image4.png"),
    subcate_image5: require("../assets/images/image5.png"),
    subcate_image6: require("../assets/images/image6.png"),
    subcate_image7: require("../assets/images/image7.png"),
    subcate_image8: require("../assets/images/image8.png"),
    subcate_image9: require("../assets/images/image9.png"),
    subcate_image12: require("../assets/images/image12.png"),
    subcate_image13: require("../assets/images/image13.png"),
    subcate_image14: require("../assets/images/image14.png"),
    subcate_image15: require("../assets/images/image15.png"),
    userimg: require("../assets/images/user.svg"),
    notemedical: require("../assets/images/notemedical.svg"),
    globe: require("../assets/images/globe.svg"),
    bell: require("../assets/images/bell.svg"),
    handshake: require("../assets/images/handshake.svg"),
    marker: require("../assets/images/marker.svg"),
    megaphone: require("../assets/images/megaphone.svg"),
    memopad: require("../assets/images/memo-pad.svg"),
    notemedical: require("../assets/images/notemedical.svg"),
    shieldexclamation: require("../assets/images/shield-exclamation.svg"),
    messagesdollar: require("../assets/images/messages-dollar.svg"),
    squarestar: require("../assets/images/square-star.svg"),
    Union3: require("../assets/images/interrogation.svg"),
    Union2: require("../assets/images/comment-alt.svg"),
    Union4: require("../assets/images/settings.svg"),


    home_img_active: require("../assets/images/houseblank_active.svg"),
    home_img_inactive: require("../assets/images/houseblank_inactive.svg"),
    
    cat_img_active: require("../assets/images/poll_active_cat.svg"),
    cat_img_inactive: require("../assets/images/poll_inactive_cat.svg"),
    
    fav_img_active: require("../assets/images/star_active.svg"),
    fav_img_inactive: require("../assets/images/starinactive.svg"),

    help_img_active: require("../assets/images/commentquestion_active.svg"),
    help_img_inactive: require("../assets/images/commentquestion_inactive.svg"),

    profile_img_active: require("../assets/images/user_active.svg"),
    profile_img_inactive: require("../assets/images/user_inactive.svg"),
  };
//const logo = require("../assets/images/wiyanwhite.png");

